version: "3.8"

services:
  api:
    image: ${REGISTRY:-ghcr.io/trypromptly/}llmstack-api:latest
    build:
      context: .
      cache_from:
        - llmstack-api:latest
    command: apiserver
    links:
      - postgres:postgres
    expose:
      - 9000
    env_file:
      - .env
    cap_add:
      - SYS_PTRACE
  rqworker:
    image: ${REGISTRY:-ghcr.io/trypromptly/}llmstack-api:latest
    build:
      context: .
      cache_from:
        - llmstack-rqworker:latest
    command: rqworker
    depends_on:
      - redis
      - postgres
    links:
      - redis:redis
      - postgres:postgres
    env_file:
      - .env
  nginx:
    image: ${REGISTRY:-ghcr.io/trypromptly/}llmstack-nginx:latest
    build:
      context: .
      dockerfile: Dockerfile.nginx
      cache_from:
        - llmstack-nginx:latest
      args:
        - REGISTRY=${REGISTRY:-ghcr.io/trypromptly/}
    ports:
      - ${LLMSTACK_PORT:-3000}:80
    env_file:
      - .env
    depends_on:
      - api
  playwright:
    image: ${REGISTRY:-ghcr.io/trypromptly/}llmstack-playwright:latest
    build:
      context: playwright
      dockerfile: Dockerfile
      cache_from:
        - llmstack-playwright:latest
    command: npx --yes playwright launch-server --browser chromium --config /config.json
    expose:
      - 30000
    ipc: host
    user: pwuser
    security_opt:
      - seccomp:playwright/seccomp_profile.json
  redis:
    image: redis:alpine
    command: redis-server
    restart: unless-stopped
    volumes:
      - ${REDIS_VOLUME}:/data
    env_file:
      - .env
  postgres:
    image: postgres:15.1-alpine
    command: "postgres -c fsync=off -c full_page_writes=off -c synchronous_commit=OFF"
    restart: unless-stopped
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_HOST_AUTH_METHOD: "password"
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER:-llmstack}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-llmstack}
    env_file:
      - .env
  weaviate:
    image: semitechnologies/weaviate:1.20.5
    volumes:
      - ${WEAVIATE_VOLUME}:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 20
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: text2vec-openai
      ENABLE_MODULES: text2vec-openai
      CLUSTER_HOSTNAME: "weaviate-node"
    env_file:
      - .env
