[llmstack]
llmstack_port=3000
redis_host="localhost"
redis_port=50379

# Platform default keys (optional)
default_openai_api_key=""
default_dreamstudio_api_key=""
default_azure_openai_api_key=""
default_cohere_api_key=""
default_forefront_api_key=""
default_elevenlabs_api_key=""

# Local installation
vector_database_engine="chroma"
vector_database_name="./llmstack.chromadb"
use_remote_job_queue="True"
cache_backend="locmem.LocMemCache"
database_name="./llmstack.sqlite"
database_engine="sqlite3"
debug="True"
playwright_url=""
generatedfiles_root="./generated_files"
site_url="http://localhost:3000"
